# name: Frontend CI/CD Pipeline

# # 1. Trigger the workflow every time code is pushed to the main branch
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # 2. Pull down the code files from our repository into the automated runner container
#       - name: Checkout Code Repository
#         uses: actions/checkout@v4

#       # 3. Securely log into AWS using our encrypted repository keys
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: eu-north-1

#       # 4. Sync our project files directly to our S3 Bucket (deleting old files that aren't in Git)
#       - name: Deploy Frontend Assets to S3
#         run: |
#           aws s3 sync . s3://baraka-cloud-resume-2026 --exclude ".git*" --exclude ".github*" --exclude "terraform*" --delete

#       # 5. Clear the global CloudFront CDN cache so the whole world instantly sees our updates
#       - name: Invalidate CloudFront Cache Distributed Nodes
#         run: |
#           aws cloudfront create-invalidation --distribution-id E2KQFNNQRKI1FJ --paths "/*" "/frontend/*" "/java-script/*" "/css-files/*"

name: Deploy Frontend to Proxmox Server

on:
  push:
    branches:
      - main # Default Branch to trigger the workflow

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Nginx Web Folder
        run: |
          cp -a . /var/www/html/
